apiVersion: v1
entries:
  helm-test11:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-26T20:41:16.0578959+03:00"
    description: A Helm chart for Kubernetes
    digest: ecaf5fdab89c25526bc6342fff98d76a010d2819d2ab1594f67e64e77841352a
    name: helm-test11
    type: application
    urls:
    - https://FadiaAlmelhem.github.io/helm-repo/helm-test11-0.1.0.tgz
    version: 0.1.0
generated: "2024-09-26T20:41:16.0555071+03:00"
